name: enviroment_flavor
description: EnviromentFlavor package.
version: 2.0.3
homepage: https://github.com/mobile-esig/enviroment_flavor

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  package_info_plus: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
